### ISSUE TITLE
Change in live url?

### ISSUE THREAD

**Issue by anupvarghese** [TheRocketLab/node-promisepay#4]
Getting the below error from promisepay request.

```
RequestError: Error: getaddrinfo ENOTFOUND api.promisepay.com api.promisepay.com:443
    at new RequestError (/usr/src/app/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/src/app/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'RequestError',
  message: 'Error: getaddrinfo ENOTFOUND api.promisepay.com api.promisepay.com:443'
```

However noticed from API docs its now pointing to `https://secure.api.promisepay.com` instead of `https://api.promisepay.com`. Should we modify?

**Comment by Maxwell2022** [comment]
Thanks for the report. Let me check this...

**Comment by Maxwell2022** [comment]
Yeah, you're right. https://docs.assemblypayments.com/feature-guides/fundamentals/environments/

Let me fix this :)

**Comment by anupvarghese** [comment]
👍  Great, that was quick

**Comment by Maxwell2022** [comment]
I published `0.0.6` to npm
API endpoints are now correct. You can also overwrite them with environment variables:

https://github.com/TheRocketLab/node-promisepay/commit/2d28e9d0806c87f8fc4f3d70133076b27a949d64

Let me know if you have any other issues. We are not using this library actively anymore so it's always good to get feedback from people using it.

**Comment by anupvarghese** [comment]
@Maxwell2022 Thanks for it.. Gonna test it now. Yeah, we will be using it and will raise issues & PRs going forward 👍

**Comment by Maxwell2022** [comment]
I've actually cleaned up the dependencies and pushed `0.1.0`.
I'm closing this issue as I think it's all good now ;)
Thanks again
